### ISSUE TITLE
kindly add 'today'

### ISSUE THREAD

**Issue by parthi2929** [bionode/timeline#1]
Hi

This is great app. Can you kindly add a vertical line to show today in Gantt?

**Comment by bmpvieira** [comment]
Hey @parthi2929 , could you please ask this on the original project repo ([auremoser/msl-gantt](https://github.com/auremoser/msl-gantt))? 

bionode/timeline is just a fork of that repo, to be used by the bionode organization.

Thanks

**Comment by parthi2929** [comment]
yes, did that thanks.
